# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='View Name')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Id')),
                ('lang_code', models.CharField(choices=[(b'en', b'English')], default=b'en', max_length=2, verbose_name='Language')),
                ('has_parameters', models.BooleanField(default=False, help_text='This indicates if the SEOMetadata path contains parameters.')),
                ('path', models.CharField(db_index=True, help_text="This should be an absolute path, excluding the domain name. Example: '/foo/bar/'. You can also capture parameters using '{X}' notation, where X is a positive number.", max_length=200, null=True, verbose_name='Path')),
                ('title', models.CharField(help_text="Here you can make use of the parameters captured in the URL using the same '{X}' notation.", max_length=100, null=True, verbose_name='Title')),
                ('description', models.CharField(help_text="Here you can make use of the parameters captured in the URL using the same '{X}' notation.", max_length=200, null=True, verbose_name='Description')),
                ('priority', models.IntegerField(default=0, help_text='Priority when duplicated. Higher the most priority. Default 0', verbose_name='Priority')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Model')),
            ],
            options={
                'ordering': ('path', 'lang_code'),
                'verbose_name': 'SEO Path Metadata',
                'verbose_name_plural': 'SEO Path Metadata',
            },
        ),
        migrations.CreateModel(
            name='SeoRegisteredModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_code', models.CharField(choices=[(b'en', b'English')], default=b'en', max_length=2, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'SEO Model',
                'verbose_name_plural': 'SEO Models',
            },
        ),
    ]
